# Generated by Django 5.2.1 on 2025-05-16 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('cv', 'CV'), ('flight', 'Flight Data'), ('finance', 'Finance'), ('wing', 'Wing Design')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.analysisinput')),
            ],
        ),
    ]
