# Generated by Django 5.2.1 on 2025-05-16 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.analysisinput')),
            ],
        ),
    ]
